
import javax.swing.JOptionPane;
import java.lang.System;
import java.sql.*;
import project.Select;


public class login extends javax.swing.JFrame {

   
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtemail2 = new javax.swing.JTextField();
        pwd2 = new javax.swing.JPasswordField();
        btnlogin2 = new javax.swing.JButton();
        btnsignin2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Login");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 71, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 37, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, -1, -1));

        txtemail2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(txtemail2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 300, -1));

        pwd2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(pwd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, 300, -1));

        btnlogin2.setBackground(new java.awt.Color(102, 0, 0));
        btnlogin2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnlogin2.setForeground(new java.awt.Color(255, 255, 255));
        btnlogin2.setText("Login");
        btnlogin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogin2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnlogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, -1, -1));

        btnsignin2.setBackground(new java.awt.Color(102, 0, 0));
        btnsignin2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnsignin2.setForeground(new java.awt.Color(255, 255, 255));
        btnsignin2.setText("Signup");
        btnsignin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignin2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnsignin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, -1, -1));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 0, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.PNG"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    int a=JOptionPane.showConfirmDialog(null,"Do you really want to close Application?","Select",JOptionPane.YES_NO_OPTION);
       if(a==0)
           System.exit(0);        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnlogin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogin2ActionPerformed
        int check=0;
        String email=txtemail2.getText();
        String password=pwd2.getText();
      
        //validation
        if(email.equals("")||password.equals(""))
        {
        check=1;
        JOptionPane.showMessageDialog(null,"Every Field Is Required");
        } 
        
        else if(email.equals("harith")&& password.equals("admin"))
        {
        check=1;
            setVisible(false);
            new adminHome().setVisible(true);
        }
        
        else
        {
        ResultSet rs=Select.getData("select *from users where email='"+email+"' and password='"+password+"'");
        try
        {
        if (rs.next())
        {
        check=1;
        if(rs.getString(5).equals("false"))
        {
            setVisible(false);
            new home().setVisible(true);
        }
        else
            JOptionPane.showMessageDialog(null,"Wait For Admin Approval");
        }
        }
        catch(Exception e)
        {
        JOptionPane.showConfirmDialog(null,e);
        }
        }
        
        if(check==0)
            JOptionPane.showMessageDialog(null,"Incorrect Email or Password");
    }//GEN-LAST:event_btnlogin2ActionPerformed

    private void btnsignin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignin2ActionPerformed
        setVisible(false);
        new signup().setVisible(true);        
    }//GEN-LAST:event_btnsignin2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogin2;
    private javax.swing.JButton btnsignin2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField pwd2;
    private javax.swing.JTextField txtemail2;
    // End of variables declaration//GEN-END:variables
}
